import type {
  Merchant,
  Customer,
  MembershipPlan,
  OwnedMembership,
  Transaction,
  Dispute,
  Ad,
  Announcement,
} from "@/types";

export const mockMerchants: Merchant[] = [
  {
    id: "merchant-1",
    walletAddress: "0xMERCH...5678",
    role: "merchant",
    name: "John's Kitchen",
    businessName: "John's Kitchen",
    description: "Farm-to-table dining",
    cuisine: "American",
    location: "123 Main St, New York",
    logo: "",
    email: "john@kitchen.com",
    phone: "+1-555-0100",
    status: "approved",
    createdAt: "2025-02-01",
    isActive: true,
  },
  {
    id: "merchant-2",
    walletAddress: "0xMERCH...ABCD",
    role: "merchant",
    name: "Sakura Sushi",
    businessName: "Sakura Sushi",
    description: "Authentic Japanese cuisine",
    cuisine: "Japanese",
    location: "456 Oak Ave, San Francisco",
    logo: "",
    email: "info@sakura.com",
    phone: "+1-555-0200",
    status: "approved",
    createdAt: "2025-02-15",
    isActive: true,
  },
  {
    id: "merchant-3",
    walletAddress: "0xMERCH...EFGH",
    role: "merchant",
    name: "Bella Italia",
    businessName: "Bella Italia",
    description: "Traditional Italian restaurant",
    cuisine: "Italian",
    location: "789 Elm St, Chicago",
    logo: "",
    email: "ciao@bellaitalia.com",
    phone: "+1-555-0300",
    status: "pending",
    createdAt: "2025-03-10",
    isActive: false,
  },
  {
    id: "merchant-4",
    walletAddress: "0xMERCH...IJKL",
    role: "merchant",
    name: "Taco Fiesta",
    businessName: "Taco Fiesta",
    description: "Mexican street food",
    cuisine: "Mexican",
    location: "321 Pine Rd, Austin",
    logo: "",
    email: "hola@tacofiesta.com",
    phone: "+1-555-0400",
    status: "pending",
    createdAt: "2025-03-20",
    isActive: false,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "customer-1",
    walletAddress: "0xCUST...9012",
    role: "customer",
    name: "Alice Smith",
    email: "alice@email.com",
    createdAt: "2025-03-01",
    isActive: true,
    ownedMemberships: ["om-1", "om-2"],
  },
  {
    id: "customer-2",
    walletAddress: "0xCUST...3456",
    role: "customer",
    name: "Bob Johnson",
    email: "bob@email.com",
    createdAt: "2025-03-05",
    isActive: true,
    ownedMemberships: ["om-3"],
  },
  {
    id: "customer-3",
    walletAddress: "0xCUST...7890",
    role: "customer",
    name: "Carol Williams",
    email: "carol@email.com",
    createdAt: "2025-03-12",
    isActive: true,
    ownedMemberships: [],
  },
];

export const mockPlans: MembershipPlan[] = [
  {
    id: "plan-1",
    merchantId: "merchant-1",
    merchantName: "John's Kitchen",
    title: "Gold Member",
    description: "10% off all meals + free dessert on birthdays",
    price: 0.05,
    duration: 365,
    benefits: [
      "10% off all meals",
      "Free birthday dessert",
      "Priority seating",
    ],
    maxSupply: 100,
    sold: 42,
    isActive: true,
    createdAt: "2025-02-10",
    tokenId: "1001",
  },
  {
    id: "plan-2",
    merchantId: "merchant-1",
    merchantName: "John's Kitchen",
    title: "Silver Member",
    description: "5% off all meals",
    price: 0.02,
    duration: 180,
    benefits: ["5% off all meals", "Monthly newsletter"],
    maxSupply: 200,
    sold: 87,
    isActive: true,
    createdAt: "2025-02-10",
    tokenId: "1002",
  },
  {
    id: "plan-3",
    merchantId: "merchant-2",
    merchantName: "Sakura Sushi",
    title: "Sushi Lover",
    description: "Unlimited miso soup + 15% off sushi platters",
    price: 0.08,
    duration: 365,
    benefits: [
      "Unlimited miso soup",
      "15% off sushi platters",
      "Chef's special access",
    ],
    maxSupply: 50,
    sold: 23,
    isActive: true,
    createdAt: "2025-02-20",
    tokenId: "2001",
  },
  {
    id: "plan-4",
    merchantId: "merchant-2",
    merchantName: "Sakura Sushi",
    title: "Sake Club",
    description: "Free sake with every dinner",
    price: 0.03,
    duration: 90,
    benefits: ["Free sake with dinner", "Happy hour pricing all day"],
    maxSupply: 150,
    sold: 65,
    isActive: true,
    createdAt: "2025-03-01",
    tokenId: "2002",
  },
];

export const mockOwnedMemberships: OwnedMembership[] = [
  {
    id: "om-1",
    planId: "plan-1",
    customerId: "customer-1",
    merchantId: "merchant-1",
    merchantName: "John's Kitchen",
    planTitle: "Gold Member",
    purchaseDate: "2025-03-05",
    expiryDate: "2026-03-05",
    txHash: "0xabc123...def456",
    tokenId: "1001",
    isValid: true,
  },
  {
    id: "om-2",
    planId: "plan-3",
    customerId: "customer-1",
    merchantId: "merchant-2",
    merchantName: "Sakura Sushi",
    planTitle: "Sushi Lover",
    purchaseDate: "2025-03-10",
    expiryDate: "2026-03-10",
    txHash: "0x789abc...123def",
    tokenId: "2001",
    isValid: true,
  },
  {
    id: "om-3",
    planId: "plan-2",
    customerId: "customer-2",
    merchantId: "merchant-1",
    merchantName: "John's Kitchen",
    planTitle: "Silver Member",
    purchaseDate: "2025-03-15",
    expiryDate: "2025-09-15",
    txHash: "0xdef789...abc012",
    tokenId: "1002",
    isValid: true,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    from: "0xCUST...9012",
    to: "merchant-1",
    amount: 0.05,
    txHash: "0xabc123...def456",
    planId: "plan-1",
    planTitle: "Gold Member",
    timestamp: "2025-03-05T10:30:00Z",
    status: "confirmed",
  },
  {
    id: "tx-2",
    from: "0xCUST...9012",
    to: "merchant-2",
    amount: 0.08,
    txHash: "0x789abc...123def",
    planId: "plan-3",
    planTitle: "Sushi Lover",
    timestamp: "2025-03-10T14:20:00Z",
    status: "confirmed",
  },
  {
    id: "tx-3",
    from: "0xCUST...3456",
    to: "merchant-1",
    amount: 0.02,
    txHash: "0xdef789...abc012",
    planId: "plan-2",
    planTitle: "Silver Member",
    timestamp: "2025-03-15T09:15:00Z",
    status: "confirmed",
  },
  {
    id: "tx-4",
    from: "0xCUST...7890",
    to: "merchant-2",
    amount: 0.03,
    txHash: "0x456def...789abc",
    planId: "plan-4",
    planTitle: "Sake Club",
    timestamp: "2025-03-20T16:45:00Z",
    status: "pending",
  },
];

export const mockDisputes: Dispute[] = [
  {
    id: "dispute-1",
    customerId: "customer-1",
    merchantId: "merchant-1",
    customerName: "Alice Smith",
    merchantName: "John's Kitchen",
    subject: "Membership not recognized at restaurant",
    description:
      "Visited the restaurant and showed my QR code but staff said it was invalid.",
    txHash: "0xabc123...def456",
    status: "open",
    createdAt: "2025-03-25",
  },
  {
    id: "dispute-2",
    customerId: "customer-2",
    merchantId: "merchant-2",
    customerName: "Bob Johnson",
    merchantName: "Sakura Sushi",
    subject: "Benefits not applied",
    description: "My 15% discount was not applied during my last visit.",
    txHash: "0xdef789...abc012",
    status: "investigating",
    createdAt: "2025-03-22",
  },
];

export const mockAds: Ad[] = [
  {
    id: "ad-1",
    merchantId: "merchant-1",
    title: "Spring Special - Gold Membership",
    description: "Get our Gold membership at 20% off this spring!",
    imageUrl: "",
    planId: "plan-1",
    isActive: true,
    createdAt: "2025-03-01",
  },
  {
    id: "ad-2",
    merchantId: "merchant-2",
    title: "Sushi Lover Launch",
    description: "New Sushi Lover membership - unlimited miso soup!",
    imageUrl: "",
    planId: "plan-3",
    isActive: true,
    createdAt: "2025-02-25",
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    merchantId: "merchant-1",
    merchantName: "John's Kitchen",
    title: "New Menu Items",
    content:
      "We've added 5 new seasonal dishes to our menu. Gold members get first access!",
    createdAt: "2025-03-20",
  },
  {
    id: "ann-2",
    merchantId: "merchant-2",
    merchantName: "Sakura Sushi",
    title: "Extended Hours",
    content:
      "We're now open until midnight on weekends. Sake Club members enjoy happy hour pricing all night!",
    createdAt: "2025-03-18",
  },
];
